name: Test and Merge

on:
  push:
    branches:
      - dev
env:
  GLOBAL_VAR: "This is available to all jobs"
  NIXPKGS_ALLOW_UNFREE: 1
  NIX_CONFIG: "experimental-features = nix-command flakes"

jobs:
  test:
    runs-on: nixos/nix:2.24.5
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          nix-channel --add https://github.com/nix-community/home-manager/archive/release-24.05.tar.gz home-manager
          nix-channel --update
          nix-shell '<home-manager>' -A install
          home-manager switch --impure --flake . --show-trace --verbose
  
  automerge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v3
      - name: Merge to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git merge --no-ff origin/dev
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
