name: Test and Merge

on:
  push:
    branches:
      - dev

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  test-build-hm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      - name: Install Home Manager
        run: |
          nix-channel --add https://github.com/nix-community/home-manager/archive/release-24.05.tar.gz home-manager && \
          nix-channel --update && \
          nix-shell '<home-manager>' -A install
      
      - name: Run tests
        run: |
          home-manager switch --impure --flake . --show-trace --verbose

  automerge:
    needs: test-build-hm
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Merge to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git merge --no-ff origin/dev
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
